name: mobile-baseline-set-v81
label: v8.1 Mobile Baseline Snippets as Set Commands
description: Mobile Basline Configuration as Set Commands
type: template
extends:

labels:
  service_type: mobile_base_panos

variables:
  - name: FW_NAME
    description: Device Name
    default: panos-01
    type_hint: text
  - name: INTF_TAP
    description: TAP Interface
    default: ethernet1/1
    type_hint: text
  - name: ZONE_TAP
    description: Zone Tapper
    default: tap
    type_hint: text
  - name: DNS_1
    description: Primary DNS Server
    default: 8.8.8.8
    type_hint: ip_address
  - name: DNS_2
    description: Secondary DNS Server
    default: 8.8.4.4
    type_hint: ip_address
  - name: NTP_1
    description: Primary NTP Server
    default: pool.ntp.org
    type_hint: ip_address
  - name: NTP_2
    description: Secondary NTP Server
    default: pool.ntp.org
    type_hint: ip_address
  - name: SFN_SERVER
    description: SafeNetworking Server IP
    default: 192.168.1.1
    type_hint: ip_address
  - name: ENODEB_SUBNET
    description: enodeB Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: MME_SUBNET
    description: MME Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: SGW_SUBNET
    description: SGW Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: SUB_SUBNET
    description: Subscriber Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: PGW_SUBNET
    description: PGW Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: PEER_SGW_SUBNET
    description: Peer SGW Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: PEER_MME_SUBNET
    description: Peer MME Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: PEER_PGW_SUBNET
    description: Peer PGW Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: HSS_SUBNET
    description: HSS Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: PEER_HSS_SUBNET
    description: Peer HSS Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: SIGTRAN_SUBNET
    description: Sigtran Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: PEER_SIGTRAN_SUBNET
    description: Peer Sigtran Subnet
    default: 192.168.1.0/24
    type_hint: ip_address

snippets:
  - name: mobile-skillet.conf
    file: mobile-skillet.conf