name: mobile-ran-set-v81
label: v8.1 Mobile RAN Snippets as Set Commands
description: Mobile RAN Configuration as Set Commands
type: template
extends:

labels:
  service_type: mobile_base_panos

variables:
  - name: ZONE_TAP
    description: Zone Tapper
    default: tap
    type_hint: text
  - name: ENODEB_SUBNET
    description: enodeB Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: MME_SUBNET
    description: MME Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: SGW_SUBNET
    description: SGW Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: SUB_SUBNET
    description: Subscriber Subnet
    default: 192.168.1.0/24
    type_hint: text

snippets:
  - name: mobile-skillet-ran.conf
    file: mobile-skillet-ran.conf