name: mobile-sigtan
label: Mobile Sigtran Snippets
description: Mobile Sigtran Configuration
type: panos
extends: mobile_baseline_panos

labels:
  service_type: mobile_panos

variables:
  - name: SIGTRAN_SUBNET
    description: Sigtran Subnet
    default: 192.168.1.0/24
    type_hint: ip_address
  - name: PEER_SIGTRAN_SUBNET
    description: Peer Sigtran Subnet
    default: 192.168.1.0/24
    type_hint: ip_address

snippets:
  - name: sigtran-addresses
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
    file: sigtran-addresses.xml
  - name: sigtran-security-rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: sigtran-security-rules.xml

