name: mobile-ran-v81
label: v8.1 Mobile RAN Snippets
description: Mobile RAN Configuration
type: panos
extends: mobile-baseline-v81

labels:
  service_type: mobile_panos

variables:
  - name: ENODEB_SUBNET
    description: enodeB Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: MME_SUBNET
    description: MME Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: SGW_SUBNET
    description: SGW Subnet
    default: 192.168.1.0/24
    type_hint: text
  - name: SUB_SUBNET
    description: Subscriber Subnet
    default: 192.168.1.0/24
    type_hint: text
  
snippets:
  - name: ran-addresses
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
    file: ran-addresses.xml
 - name: roaming-address-groups
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address-group
    file: ran-address-groups.xml
  - name: ran-security-rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: ran-security-rules.xml

